default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: root
development:
  <<: *default
  database: air_development
  host: localhost
  username: root
  password: root

# pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>