:concurrency: 10
:logfile: ./log/sidekiq.log
#:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 25
development:
  :concurrency: 10
production:
  :concurrency: 25

:queues:
  - default
  - insert_unique_routes_worker
  - identify_flight_schedule_collective_worker
  - identify_airline_brand_collective_worker
  - identify_flight_ticket_collective_worker